services:
  dashboard:
    image: fscarmen/argo-nezha:latest
    ports:
      - "80:80"
    environment:
      GH_USER: xiaozhou26
      GH_CLIENTID: 04ce5845fb4b6aea93e3
      GH_CLIENTSECRET: a8fe24ea9f2215893a1f387ed951ef9b9e54241d
      GH_BACKUP_USER: xiaozhou26
      GH_REPO: natuo
      GH_EMAIL: xiaofei@angelxf.tk
      GH_PAT: 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
      ARGO_AUTH: ${ARGO_AUTH}
      ARGO_DOMAIN: tz.xfvps.eu.org
